/*
 *
 * FrontPage constants
 *
 */

export const LOAD_FRONT_PAGE_POSTS_PENDING = 'app/FrontPage/LOAD_FRONT_PAGE_POSTS_PENDING';
export const LOAD_FRONT_PAGE_POSTS_SUCCESS = 'app/FrontPage/LOAD_FRONT_PAGE_POSTS_SUCCESS';
export const LOAD_FRONT_PAGE_POSTS_FAILED = 'app/FrontPage/LOAD_FRONT_PAGE_POSTS_FAILED';
