/*
 *
 * Player constants
 *
 */

export const PLAY_LIVE = 'app/Player/PLAY_LIVE';

export const GET_PODCAST_PLAYLIST_PENDING = 'app/Player/GET_PODCAST_PLAYLIST_PENDING';
export const GET_PODCAST_PLAYLIST_SUCCESS = 'app/Player/GET_PODCAST_PLAYLIST_SUCCESS';
export const GET_PODCAST_PLAYLIST_FAIELD = 'app/Player/GET_PODCAST_PLAYLIST_FAIELD';

export const GET_ON_DEMAND_PLAYLIST_PENDING = 'app/Player/GET_ON_DEMAND_PLAYLIST_PENDING';
export const GET_ON_DEMAND_PLAYLIST_SUCCESS = 'app/Player/GET_ON_DEMAND_PLAYLIST_SUCCESS';
export const GET_ON_DEMAND_PLAYLIST_FAIELD = 'app/Player/GET_ON_DEMAND_PLAYLIST_FAIELD';
