/*
 *
 * ShowAdmin constants
 *
 */

export const ADD_SHOW_PENDING = 'app/ShowAdmin/ADD_SHOW_PENDING';
export const ADD_SHOW_SUCCESS = 'app/ShowAdmin/ADD_SHOW_SUCCESS';
export const ADD_SHOW_FAILED = 'app/ShowAdmin/ADD_SHOW_FAILED';

export const LOAD_DIGAS_SHOWS_PENDING = 'app/ShowAdmin/LOAD_DIGAS_SHOWS_PENDING';
export const LOAD_DIGAS_SHOWS_SUCCESS = 'app/ShowAdmin/LOAD_DIGAS_SHOWS_SUCCESS';
export const LOAD_DIGAS_SHOWS_FAILED = 'app/ShowAdmin/LOAD_DIGAS_SHOWS_FAILED';

export const LOAD_DIGAS_PODCASTURL_PENDING = 'app/ShowAdmin/LOAD_DIGAS_PODCASTURL_PENDING';
export const LOAD_DIGAS_PODCASTURL_SUCCESS = 'app/ShowAdmin/LOAD_DIGAS_PODCASTURL_SUCCESS';
export const LOAD_DIGAS_PODCASTURL_FAILED = 'app/ShowAdmin/LOAD_DIGAS_PODCASTURL_FAILED';

export const CLEAR_DIGAS_PODCASTURL = 'app/ShowAdmin/CLEAR_DIGAS_PODCASTURL';
